name = "friend-flow"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[triggers]
crons = ["*/30 * * * *", "0 17 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "friend-flow-db"
database_id = "091261cc-3784-43b7-ada3-6de68914011f"

[vars]
GITHUB_RAW_BASE = "https://ainzrimuru.github.io/friend_flow_apply"
IMAGES_BASE = "https://friend-cdn.rimuru.work"

[assets]
directory = "./frontend/dist"
